version: '3.1'
services:
  fetch:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fetch-service
    ports:
      - 8888:8888
  docs:
    build:
      context: ./
      dockerfile: Dockerfile.docs
    container_name: docs-service
    ports:
      - 80:8080